[tool.poetry]
name = "toychain"
version = "0.1.0"
description = "A blockchain toy project, in Python"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
flask = "0.12.2"
requests = "^2.23.0"
loguru = "^0.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
